Persist circuits in batch execute
amazon-braket/amazon-braket-pennylane-plugin-python pull request #260
Opened 2024-05-30 10:40 UTC by WingCode

*Issue #, if available:* closes #255

*Description of changes:* Add persistence of multiple circuits when batch_execute is called

*Testing done:* 

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/README.md) and [API docs](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-05-31 19:26 UTC, math411 commented
Hi @WingCode and thanks for raising this! It seems the linter check is failing. Locally, you can run `tox -e linters` to fix this.

2024-06-11 16:54 UTC, WingCode commented
@math411 Could you please review?

2024-06-11 19:48 UTC, yitchen-tim requested changes
Hi @WingCode , thanks for contributing to the issue! This PR solves half of the problem stated in https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/issues/255. Printing noisy circuits when using noise model is still not supported. However, after reviewing this PR, I think printing noisy circuits is not the right goal to pursue.

The right goal is to allow users to retrieve the tasks (and the task ids), from which noisy circuits can be retrieved. If you can extend this PR to include the following feature, we are good to go: "Persist the task when parallel=True", which requires

1. Add an attribute `self._tasks=[]`
2. Add a method for returning tasks
```
    @property
    def tasks(self) -> list[QuantumTask]:
        ...
``` 
, similar to 
https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/a17e8b99c8089dde79786729ad482af08e3b3431/src/braket/pennylane_plugin/braket_device.py#L179
3. Add unit tests for `tasks`

2024-06-11 19:48 UTC, yitchen-tim commented on src/braket/pennylane_plugin/braket_device.py
> +        self.circuits = []
```suggestion
        self._circuits = []
```

2024-06-11 19:48 UTC, yitchen-tim commented on src/braket/pennylane_plugin/braket_device.py
> +            self.circuits.append(circuit)
```suggestion
        self._circuits = braket_circuits
```

2024-06-11 19:48 UTC, yitchen-tim commented on src/braket/pennylane_plugin/braket_device.py
> +        self._circuits = []
`self._circuits` here is a private variable. that users should not access. Instead, users access _circuits through properties. So, there need to be a new property of this class called `circuits` defined as a method of the class, similar to  https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/a17e8b99c8089dde79786729ad482af08e3b3431/src/braket/pennylane_plugin/braket_device.py#L174.

2024-06-11 19:48 UTC, yitchen-tim commented on src/braket/pennylane_plugin/braket_device.py
> +        self._circuits = []
And yes, it's a bit repetitive now that we have both `circuits` and `circuit`, but I think it's okay for now. In long term, `circuit` may be deprecated.

2024-06-11 19:48 UTC, yitchen-tim commented on src/braket/pennylane_plugin/braket_device.py
> +            self.circuits.append(circuit)
^ Note: this suggestion also moves the code out of the for loop

2024-06-12 03:19 UTC, yitchen-tim approved these changes
Hi @WingCode, the PR looks good! I changed the target branch to be a feature branch instead of the main branch because Amazon Braket needs rework the duplication of `circuit` and `circuits` which requires some discussions. I will assign the issue to you and close the issue. This should be good in UnitaryHack regards. Thanks for contributing! 

 I somehow have trouble assigning the issue to you. I am asking my team to resolve it.

2024-06-12 05:16 UTC, WingCode commented
Thank you @yitchen-tim for the reviews and all of the timely support!

2024-06-12 13:56 UTC, yitchen-tim commented
@WingCode Could you leave a comment on the issue: https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/issues/255? After that, I should be able to assign you.

2024-06-12 16:49 UTC, merged